name: DCO Check

on:
  pull_request:
    branches: [ master ]

jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
    - name: Check DCO
      uses: tim-actions/dco@v1.1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}